import { GameShell } from './ui/game-shell.js';

const dom = {
  catalogSearch: document.querySelector('#catalog-search'),
  gameSelector: document.querySelector('#game-selector'),
  gameSummary: document.querySelector('#game-summary'),
  gameIdBadge: document.querySelector('#game-id-badge'),
  gameSourceBadge: document.querySelector('#game-source-badge'),
  gameComplexityBadge: document.querySelector('#game-complexity-badge'),
  gameTags: document.querySelector('#game-tags'),
  gameMetaText: document.querySelector('#game-meta-text'),
  templateSelector: document.querySelector('#template-selector'),
  loadTemplateButton: document.querySelector('#load-template-button'),
  templateSummary: document.querySelector('#template-summary'),
  playerOneController: document.querySelector('#player-one-controller'),
  playerTwoController: document.querySelector('#player-two-controller'),
  minimaxDepth: document.querySelector('#minimax-depth'),
  mctsIterations: document.querySelector('#mcts-iterations'),
  restartButton: document.querySelector('#restart-button'),
  runAiButton: document.querySelector('#run-ai-button'),
  undoButton: document.querySelector('#undo-button'),
  redoButton: document.querySelector('#redo-button'),
  analyzeButton: document.querySelector('#analyze-button'),
  statusText: document.querySelector('#status-text'),
  legend: document.querySelector('#legend'),
  featureList: document.querySelector('#feature-list'),
  boardTitle: document.querySelector('#board-title'),
  turnIndicator: document.querySelector('#turn-indicator'),
  boardStats: document.querySelector('#board-stats'),
  boardContainer: document.querySelector('#board-container'),
  boardHint: document.querySelector('#board-hint'),
  ruleSummary: document.querySelector('#rule-summary'),
  aiSummary: document.querySelector('#ai-summary'),
  learningStatus: document.querySelector('#learning-status'),
  moveLog: document.querySelector('#move-log'),
  timelineSlider: document.querySelector('#timeline-slider'),
  timelineLabel: document.querySelector('#timeline-label'),
  analysisStatus: document.querySelector('#analysis-status'),
  analysisOverview: document.querySelector('#analysis-overview'),
  analysisNotes: document.querySelector('#analysis-notes'),
  minimaxCandidates: document.querySelector('#minimax-candidates'),
  mctsCandidates: document.querySelector('#mcts-candidates'),
  learnedCandidates: document.querySelector('#learned-candidates'),
  definitionEditor: document.querySelector('#definition-editor'),
  validateDefinitionButton: document.querySelector('#validate-definition-button'),
  formatDefinitionButton: document.querySelector('#format-definition-button'),
  applyDefinitionButton: document.querySelector('#apply-definition-button'),
  saveDefinitionButton: document.querySelector('#save-definition-button'),
  snapshotDefinitionButton: document.querySelector('#snapshot-definition-button'),
  resetEditorButton: document.querySelector('#reset-editor-button'),
  deleteCustomButton: document.querySelector('#delete-custom-button'),
  studioStatus: document.querySelector('#studio-status'),
  definitionHealth: document.querySelector('#definition-health'),
  definitionQualityNotes: document.querySelector('#definition-quality-notes'),
  definitionDiagnostics: document.querySelector('#definition-diagnostics'),
  definitionPreview: document.querySelector('#definition-preview'),
  draftList: document.querySelector('#draft-list'),
  copyShareButton: document.querySelector('#copy-share-button'),
  exportJsonButton: document.querySelector('#export-json-button'),
  importJsonButton: document.querySelector('#import-json-button'),
  importJsonInput: document.querySelector('#import-json-input'),
  arenaControllerA: document.querySelector('#arena-controller-a'),
  arenaControllerB: document.querySelector('#arena-controller-b'),
  arenaMatchCount: document.querySelector('#arena-match-count'),
  arenaHardLimit: document.querySelector('#arena-hard-limit'),
  arenaSeed: document.querySelector('#arena-seed'),
  arenaSwapSides: document.querySelector('#arena-swap-sides'),
  arenaRunButton: document.querySelector('#arena-run-button'),
  arenaExportButton: document.querySelector('#arena-export-button'),
  arenaStatus: document.querySelector('#arena-status'),
  arenaSummary: document.querySelector('#arena-summary'),
  arenaResults: document.querySelector('#arena-results'),
};

const shell = new GameShell(dom);
window.gameGenome = shell;

shell.initialize().catch((error) => {
  console.error(error);
  dom.statusText.textContent = `初期化に失敗しました: ${error.message}`;
  dom.studioStatus.textContent = `初期化に失敗しました: ${error.message}`;
});
